DEVELOPMENT: true
LOGGING: true

# This will fire fake events; use this if you want to run the project
# outside of the add-on
USE_SHIM: true

# This is the embedly proxy server
# File issues at https://github.com/mozilla/embedly-proxy/issues
EMBEDLY_ENDPOINT: ""
